-- MySQL Script generated by MySQL Workbench
-- Sun 15 Mar 2015 09:30:10 PM GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema perfect_score
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema perfect_score
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `perfect_score` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `perfect_score` ;

-- -----------------------------------------------------
-- Table `perfect_score`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfect_score`.`tests` (
  `_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perfect_score`.`tests_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfect_score`.`tests_questions` (
  `question` VARCHAR(45) NOT NULL,
  `test` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`question`, `test`),
  INDEX `test_idx` (`test` ASC),
  CONSTRAINT `test`
    FOREIGN KEY (`test`)
    REFERENCES `perfect_score`.`tests` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
